#pragma once


class CCategoryDataDB
{
	static const INT64 nClass = 0x00BEEAE8;
public:
	enum Category
	{
		FIGHTER_GROUP = 0,
		MAGE_GROUP = 1,
		WIZARD_GROUP = 2,
		CLERIC_GROUP = 3,
		ATTACKER_GROUP = 4,
		FIRST_CLASS_GROUP = 5,
		SECOND_CLASS_GROUP = 6,
		THIRD_CLASS_GROUP = 7,
		FOURTH_CLASS_GROUP = 8,
		BOUNTY_HUNTER_GROUP = 9,
		WARSMITH_GROUP = 10,
		SUMMON_NPC_GROUP = 11,
		KNIGHT_GROUP = 12,
		WHITE_MAGIC_GROUP = 13,
		HEAL_GROUP = 14,
		ASSIST_MAGIC_GROUP = 15,
		WARRIOR_GROUP = 16,
		HUMAN_2ND_GROUP = 17,
		ELF_2ND_GROUP = 18,
		DELF_2ND_GROUP = 19,
		ORC_2ND_GROUP = 20,
		DWARF_2ND_GROUP = 21,
		STRIDER = 22,
		PET_GROUP = 23,
		SUBJOB_GROUP_DAGGER = 24,
		SUBJOB_GROUP_BOW = 25,
		SUBJOB_GROUP_KNIGHT = 26,
		SUBJOB_GROUP_SUMMONER = 27,
		SUBJOB_GROUP_HALF_HEALER = 28,
		SUBJOB_GROUP_DANCE = 29,
		SUBJOB_GROUP_WIZARD = 30,
		HUMAN_FALL_CLASS = 31,
		HUMAN_WALL_CLASS = 32,
		HUMAN_MALL_CLASS = 33,
		HUMAN_CALL_CLASS = 34,
		ELF_FALL_CLASS = 35,
		ELF_MALL_CLASS = 36,
		ELF_WALL_CLASS = 37,
		ELF_CALL_CLASS = 38,
		DELF_FALL_CLASS = 39,
		DELF_MALL_CLASS = 40,
		DELF_WALL_CLASS = 41,
		DELF_CALL_CLASS = 42,
		ORC_FALL_CLASS = 43,
		ORC_MALL_CLASS = 44,
		DWARF_ALL_CLASS = 45,
		DWARF_BOUNTY_CLASS = 46,
		DWARF_SMITH_CLASS = 47
	};
	static bool IsInCategory(int nClassID, int nCategoryID)
	{
		typedef bool (*_iic)(INT64, int, int);
		_iic iic = (_iic) 0x004AEDF0;
		return iic(nClass, nClassID, nCategoryID);
	}
};