#pragma once

enum NPC_OP_CODE_IN
{
	TEST_NPC_OPCODE,
	INITIALIZE_ERA,
	PROCESSING_ERA_NPC_DONE,
	CHANGE_ERA,
	TELEPORT_MPCC,
	TELEPORT_MPCC_BY_INDEX,
	SET_PC_LEVEL,
	ADD_PC_SOCIAL,
	UPDATE_PLEDGE_NAME_VALUE
};